project_id = "twrluuhkfhjkxmelrhct"

[functions.get-project-file-url]
verify_jwt = false

[functions.get-public-file-url]
verify_jwt = false

[functions.get-public-file-urls]
verify_jwt = false

[functions.generate-invoice-pdf]
verify_jwt = false

[functions.import-drive-pdf]
verify_jwt = false